//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated based on the Unicorn serialisation items
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable InconsistentNaming
namespace [projectName].Feature.Demo
{
	using global::Sitecore.Data;

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
    public struct SitecoreTemplates
    {
	
		/// <summary>
		/// Demo
		/// <para></para>
		/// <para>Path: /sitecore/templates/[projectName]/Feature/Demo/Demo</para>	
		/// <para>ID: 3b2b0676-71c3-4bd1-aa3b-05138f63c221</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Demo
        {
			/// <summary>
			/// The ID for /sitecore/templates/[projectName]/Feature/Demo/Demo
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{3b2b0676-71c3-4bd1-aa3b-05138f63c221}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/[projectName]/Feature/Demo/Demo
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "3b2b0676-71c3-4bd1-aa3b-05138f63c221";

			public struct Text
            {
				/// <summary>
				/// The Text field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "Text";

				/// <summary>
				/// The ID for Text field 
				/// </summary>
                public static ID FieldId = new ID("{ee5d7eae-69a7-4c0c-ad91-370eac6b05c5}");
            }
		}
	}
}